name: Claude Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  claude-response:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
    - name: Claude Assistant
      uses: anthropics/claude-code-base-action@main
      with:
        anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
        prompt: "You are Claude, an AI assistant integrated with GitHub. Please help with code reviews, answer questions about the codebase, and assist with development tasks. Respond to issues and comments in a helpful and professional manner."